services:
  - type: web
    name: sulfurdocs-api
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /health

    envVars:
      - key: MONGO_CONNECTION
        sync: false

      - key: JWT_SECRET
        generateValue: true

      - key: FRONTEND_URL
        sync: false